// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepositoryLayer;

#nullable disable

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RepositoryLayer.Entity.SignalForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CssClasses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FormType")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SignalForm", "DynamicSignalForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The first form (basic)"
                        },
                        new
                        {
                            Id = 2,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The second form (callbacks)"
                        },
                        new
                        {
                            Id = 3,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The third form (start- and enddate)"
                        },
                        new
                        {
                            Id = 4,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The fourth form (autocomplete)"
                        },
                        new
                        {
                            Id = 5,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The fifth form (number inputs)"
                        },
                        new
                        {
                            Id = 6,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The sixth form (single select)."
                        },
                        new
                        {
                            Id = 7,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The seventh form (multiple select)."
                        },
                        new
                        {
                            Id = 8,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The eighth form (radiobuttons)."
                        },
                        new
                        {
                            Id = 9,
                            CssClasses = "column w-50 p-1",
                            FormType = 1,
                            Title = "The ninth form (todo-list parent)."
                        },
                        new
                        {
                            Id = 10,
                            CssClasses = "row w-50",
                            FormType = 2,
                            Title = "The tenth form (form array)."
                        });
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormAdditionalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AttributeType")
                        .HasColumnType("integer");

                    b.Property<int>("SignalFormFieldId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SignalFormFieldId");

                    b.ToTable("SignalFormAdditionalData", "DynamicSignalForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attribute = "cols",
                            AttributeType = 2,
                            SignalFormFieldId = 4,
                            Value = "30"
                        },
                        new
                        {
                            Id = 2,
                            Attribute = "rows",
                            AttributeType = 2,
                            SignalFormFieldId = 4,
                            Value = "5"
                        },
                        new
                        {
                            Id = 3,
                            Attribute = "cols",
                            AttributeType = 2,
                            SignalFormFieldId = 8,
                            Value = "30"
                        },
                        new
                        {
                            Id = 4,
                            Attribute = "rows",
                            AttributeType = 2,
                            SignalFormFieldId = 8,
                            Value = "5"
                        });
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CssClasses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("FormArrayId")
                        .HasColumnType("integer");

                    b.Property<string>("InitialValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InputType")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Property")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PropertyType")
                        .HasColumnType("integer");

                    b.Property<int?>("SignalFormId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SignalFormId");

                    b.ToTable("SignalFormField", "DynamicSignalForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 1,
                            Label = "Firstname",
                            Property = "firstname",
                            PropertyType = 1,
                            SignalFormId = 1
                        },
                        new
                        {
                            Id = 2,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 1,
                            Label = "Lastname",
                            Property = "lastname",
                            PropertyType = 1,
                            SignalFormId = 1
                        },
                        new
                        {
                            Id = 3,
                            CssClasses = "column",
                            InitialValue = "18",
                            InputType = 5,
                            Label = "Age",
                            Property = "age",
                            PropertyType = 2,
                            SignalFormId = 1
                        },
                        new
                        {
                            Id = 4,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 15,
                            Label = "Information about Person",
                            Property = "information",
                            PropertyType = 1,
                            SignalFormId = 1
                        },
                        new
                        {
                            Id = 5,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 2,
                            Label = "Firstname",
                            Property = "firstname",
                            PropertyType = 1,
                            SignalFormId = 2
                        },
                        new
                        {
                            Id = 6,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 2,
                            Label = "Lastname",
                            Property = "lastname",
                            PropertyType = 1,
                            SignalFormId = 2
                        },
                        new
                        {
                            Id = 7,
                            CssClasses = "column",
                            InitialValue = "18",
                            InputType = 6,
                            Label = "Age",
                            Property = "age",
                            PropertyType = 2,
                            SignalFormId = 2
                        },
                        new
                        {
                            Id = 8,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 16,
                            Label = "Information about Person",
                            Property = "information",
                            PropertyType = 1,
                            SignalFormId = 2
                        },
                        new
                        {
                            Id = 9,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 9,
                            Label = "Startdate (from today until 30 days)",
                            Property = "startdate",
                            PropertyType = 10,
                            SignalFormId = 3
                        },
                        new
                        {
                            Id = 10,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 9,
                            Label = "Enddate (from today until 30 days)",
                            Property = "enddate",
                            PropertyType = 10,
                            SignalFormId = 3
                        },
                        new
                        {
                            Id = 11,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 3,
                            Label = "Favorite Fruit",
                            Property = "fruit",
                            PropertyType = 1,
                            SignalFormId = 4
                        },
                        new
                        {
                            Id = 12,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 4,
                            Label = "Favorite Car",
                            Property = "car",
                            PropertyType = 1,
                            SignalFormId = 4
                        },
                        new
                        {
                            Id = 13,
                            CssClasses = "column",
                            InitialValue = "10.00",
                            InputType = 7,
                            Label = "Your bid for second hand book (10.00 - 100.00)",
                            Property = "bid",
                            PropertyType = 2,
                            SignalFormId = 5
                        },
                        new
                        {
                            Id = 14,
                            CssClasses = "column",
                            InitialValue = "16.00",
                            InputType = 8,
                            Label = "Enter value between -25.00 and 25.00",
                            Property = "valuebetween",
                            PropertyType = 2,
                            SignalFormId = 5
                        },
                        new
                        {
                            Id = 15,
                            CssClasses = "column",
                            InitialValue = "25",
                            InputType = 5,
                            Label = "Random Positive Number (10 - 75)",
                            Property = "randompositivenumber",
                            PropertyType = 2,
                            SignalFormId = 5
                        },
                        new
                        {
                            Id = 16,
                            CssClasses = "column",
                            InitialValue = "-25",
                            InputType = 6,
                            Label = "Random Negative Number (from -10 to -75)",
                            Property = "randomnegativenumber",
                            PropertyType = 2,
                            SignalFormId = 5
                        },
                        new
                        {
                            Id = 17,
                            CssClasses = "column",
                            InitialValue = "Saskia",
                            InputType = 11,
                            Label = "Select Girl Name",
                            Property = "selectgirlname",
                            PropertyType = 1,
                            SignalFormId = 6
                        },
                        new
                        {
                            Id = 18,
                            CssClasses = "column",
                            InitialValue = "White",
                            InputType = 12,
                            Label = "Select Color",
                            Property = "selectcolor",
                            PropertyType = 1,
                            SignalFormId = 6
                        },
                        new
                        {
                            Id = 19,
                            CssClasses = "column",
                            InitialValue = "Natasha, Jasmine",
                            InputType = 13,
                            Label = "Select Girl Names",
                            Property = "select_girl_names_multi",
                            PropertyType = 4,
                            SignalFormId = 7
                        },
                        new
                        {
                            Id = 20,
                            CssClasses = "column",
                            InitialValue = "Hamster, Rabbit",
                            InputType = 14,
                            Label = "Select Animals",
                            Property = "select_animals_multi",
                            PropertyType = 4,
                            SignalFormId = 7
                        },
                        new
                        {
                            Id = 21,
                            CssClasses = "column",
                            InitialValue = "1",
                            InputType = 17,
                            Label = "Select Option",
                            Property = "select_option",
                            PropertyType = 2,
                            SignalFormId = 8
                        },
                        new
                        {
                            Id = 22,
                            CssClasses = "column",
                            InitialValue = "0",
                            InputType = 18,
                            Label = "Select Choice",
                            Property = "select_choice",
                            PropertyType = 2,
                            SignalFormId = 8
                        },
                        new
                        {
                            Id = 23,
                            CssClasses = "column",
                            InitialValue = "false",
                            InputType = 19,
                            Label = "I agree to the general conditions",
                            Property = "general_conditions",
                            PropertyType = 3,
                            SignalFormId = 8
                        },
                        new
                        {
                            Id = 24,
                            CssClasses = "column",
                            InitialValue = "true",
                            InputType = 20,
                            Label = "I agree with the service agreement (default: true)",
                            Property = "service_agreement",
                            PropertyType = 3,
                            SignalFormId = 8
                        },
                        new
                        {
                            Id = 25,
                            CssClasses = "column mb-1",
                            InitialValue = "false",
                            InputType = 21,
                            Label = "Confirm agreements",
                            Property = "confirm_agreements",
                            PropertyType = 3,
                            SignalFormId = 8
                        },
                        new
                        {
                            Id = 26,
                            CssClasses = "column mb-1",
                            InitialValue = "true",
                            InputType = 22,
                            Label = "I read and understand all agreements",
                            Property = "read_agreements",
                            PropertyType = 3,
                            SignalFormId = 8
                        },
                        new
                        {
                            Id = 27,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 1,
                            Label = "My Todo List",
                            Property = "title",
                            PropertyType = 1,
                            SignalFormId = 9
                        },
                        new
                        {
                            Id = 28,
                            CssClasses = "",
                            FormArrayId = 10,
                            InitialValue = "",
                            InputType = 23,
                            Label = "FORM_ARRAY",
                            Property = "todos",
                            PropertyType = 9,
                            SignalFormId = 9
                        },
                        new
                        {
                            Id = 29,
                            CssClasses = "column",
                            InitialValue = "",
                            InputType = 1,
                            Label = "Task",
                            Property = "task",
                            PropertyType = 1,
                            SignalFormId = 10
                        },
                        new
                        {
                            Id = 30,
                            CssClasses = "column pt-1 ms-1",
                            InitialValue = "false",
                            InputType = 21,
                            Label = "Completed?",
                            Property = "completed",
                            PropertyType = 3,
                            SignalFormId = 10
                        });
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SignalFormFieldId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeOfValue")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SignalFormFieldId");

                    b.ToTable("SignalFormOption", "DynamicSignalForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "ananas",
                            SignalFormFieldId = 11,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 2,
                            Label = "apple",
                            SignalFormFieldId = 11,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 3,
                            Label = "banana",
                            SignalFormFieldId = 11,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 4,
                            Label = "black berry",
                            SignalFormFieldId = 11,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 5,
                            Label = "peach",
                            SignalFormFieldId = 11,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 6,
                            Label = "pear",
                            SignalFormFieldId = 11,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 7,
                            Label = "strawberry",
                            SignalFormFieldId = 11,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 8,
                            Label = "Alfa Romeo",
                            SignalFormFieldId = 12,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 9,
                            Label = "Batmobile",
                            SignalFormFieldId = 12,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 10,
                            Label = "Ferrari",
                            SignalFormFieldId = 12,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 11,
                            Label = "Lada",
                            SignalFormFieldId = 12,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 12,
                            Label = "Lamborghini",
                            SignalFormFieldId = 12,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 13,
                            Label = "Mercedes",
                            SignalFormFieldId = 12,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 14,
                            Label = "Porsche",
                            SignalFormFieldId = 12,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 15,
                            Label = "Saskia",
                            SignalFormFieldId = 17,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 16,
                            Label = "Matilda",
                            SignalFormFieldId = 17,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 17,
                            Label = "Juliette",
                            SignalFormFieldId = 17,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 18,
                            Label = "Caroline",
                            SignalFormFieldId = 17,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 19,
                            Label = "Victoria",
                            SignalFormFieldId = 17,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 20,
                            Label = "Abigaïl",
                            SignalFormFieldId = 17,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 21,
                            Label = "Caitlin",
                            SignalFormFieldId = 17,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 22,
                            Label = "Black",
                            SignalFormFieldId = 18,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 23,
                            Label = "Blue",
                            SignalFormFieldId = 18,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 24,
                            Label = "Green",
                            SignalFormFieldId = 18,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 25,
                            Label = "Red",
                            SignalFormFieldId = 18,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 26,
                            Label = "Turquoise",
                            SignalFormFieldId = 18,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 27,
                            Label = "Yellow",
                            SignalFormFieldId = 18,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 28,
                            Label = "White",
                            SignalFormFieldId = 18,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 29,
                            Label = "Dorothy",
                            SignalFormFieldId = 19,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 30,
                            Label = "Jasmine",
                            SignalFormFieldId = 19,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 31,
                            Label = "Lydia",
                            SignalFormFieldId = 19,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 32,
                            Label = "Natasha",
                            SignalFormFieldId = 19,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 33,
                            Label = "Savannah",
                            SignalFormFieldId = 19,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 34,
                            Label = "Serana",
                            SignalFormFieldId = 19,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 35,
                            Label = "Triss",
                            SignalFormFieldId = 19,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 36,
                            Label = "Cat",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 37,
                            Label = "Dog",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 38,
                            Label = "Ferret",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 39,
                            Label = "Goldfish",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 40,
                            Label = "Guinea pig",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 41,
                            Label = "Hamster",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 42,
                            Label = "Horse",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 43,
                            Label = "Lizard",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 44,
                            Label = "Mouse",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 45,
                            Label = "Parrot",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 46,
                            Label = "Rabbit",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 47,
                            Label = "Sheep",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 48,
                            Label = "Turtle",
                            SignalFormFieldId = 20,
                            TypeOfValue = 0,
                            Value = ""
                        },
                        new
                        {
                            Id = 49,
                            Label = "Option 1",
                            SignalFormFieldId = 21,
                            TypeOfValue = 2,
                            Value = "1"
                        },
                        new
                        {
                            Id = 50,
                            Label = "Option 2",
                            SignalFormFieldId = 21,
                            TypeOfValue = 2,
                            Value = "2"
                        },
                        new
                        {
                            Id = 51,
                            Label = "Option 3",
                            SignalFormFieldId = 21,
                            TypeOfValue = 2,
                            Value = "3"
                        },
                        new
                        {
                            Id = 52,
                            Label = "Yes, I want to receive newsletters",
                            SignalFormFieldId = 22,
                            TypeOfValue = 2,
                            Value = "1"
                        },
                        new
                        {
                            Id = 53,
                            Label = "Yes, I want to receive alerts",
                            SignalFormFieldId = 22,
                            TypeOfValue = 2,
                            Value = "2"
                        },
                        new
                        {
                            Id = 54,
                            Label = "Yes, I want to receive newsletters and alerts",
                            SignalFormFieldId = 22,
                            TypeOfValue = 2,
                            Value = "3"
                        },
                        new
                        {
                            Id = 55,
                            Label = "No thanks, I don't want to receive newsletters and alerts",
                            SignalFormFieldId = 22,
                            TypeOfValue = 2,
                            Value = "0"
                        });
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SignalFormFieldId")
                        .HasColumnType("integer");

                    b.Property<int>("Validation")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SignalFormFieldId");

                    b.ToTable("SignalFormValidation", "DynamicSignalForms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SignalFormFieldId = 1,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 2,
                            SignalFormFieldId = 2,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 3,
                            SignalFormFieldId = 3,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 4,
                            SignalFormFieldId = 3,
                            Validation = 4,
                            Value = "18"
                        },
                        new
                        {
                            Id = 5,
                            SignalFormFieldId = 3,
                            Validation = 5,
                            Value = "65"
                        },
                        new
                        {
                            Id = 6,
                            SignalFormFieldId = 4,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 7,
                            SignalFormFieldId = 4,
                            Validation = 3,
                            Value = "250"
                        },
                        new
                        {
                            Id = 8,
                            SignalFormFieldId = 5,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 9,
                            SignalFormFieldId = 6,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 10,
                            SignalFormFieldId = 7,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 11,
                            SignalFormFieldId = 7,
                            Validation = 4,
                            Value = "18"
                        },
                        new
                        {
                            Id = 12,
                            SignalFormFieldId = 7,
                            Validation = 5,
                            Value = "65"
                        },
                        new
                        {
                            Id = 13,
                            SignalFormFieldId = 8,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 14,
                            SignalFormFieldId = 8,
                            Validation = 3,
                            Value = "250"
                        },
                        new
                        {
                            Id = 15,
                            SignalFormFieldId = 9,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 16,
                            SignalFormFieldId = 9,
                            Validation = 9,
                            Value = "0"
                        },
                        new
                        {
                            Id = 17,
                            SignalFormFieldId = 9,
                            Validation = 13,
                            Value = "30"
                        },
                        new
                        {
                            Id = 18,
                            SignalFormFieldId = 9,
                            Validation = 17,
                            Value = "enddate"
                        },
                        new
                        {
                            Id = 19,
                            SignalFormFieldId = 9,
                            Validation = 18,
                            Value = "enddate"
                        },
                        new
                        {
                            Id = 20,
                            SignalFormFieldId = 10,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 21,
                            SignalFormFieldId = 10,
                            Validation = 9,
                            Value = "0"
                        },
                        new
                        {
                            Id = 22,
                            SignalFormFieldId = 10,
                            Validation = 13,
                            Value = "30"
                        },
                        new
                        {
                            Id = 23,
                            SignalFormFieldId = 10,
                            Validation = 17,
                            Value = "startdate"
                        },
                        new
                        {
                            Id = 24,
                            SignalFormFieldId = 10,
                            Validation = 19,
                            Value = "startdate"
                        },
                        new
                        {
                            Id = 25,
                            SignalFormFieldId = 11,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 26,
                            SignalFormFieldId = 12,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 27,
                            SignalFormFieldId = 13,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 28,
                            SignalFormFieldId = 13,
                            Validation = 7,
                            Value = "10.00"
                        },
                        new
                        {
                            Id = 29,
                            SignalFormFieldId = 13,
                            Validation = 8,
                            Value = "100.00"
                        },
                        new
                        {
                            Id = 30,
                            SignalFormFieldId = 14,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 31,
                            SignalFormFieldId = 14,
                            Validation = 7,
                            Value = "-25.00"
                        },
                        new
                        {
                            Id = 32,
                            SignalFormFieldId = 14,
                            Validation = 8,
                            Value = "25.00"
                        },
                        new
                        {
                            Id = 33,
                            SignalFormFieldId = 15,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 34,
                            SignalFormFieldId = 15,
                            Validation = 4,
                            Value = "10"
                        },
                        new
                        {
                            Id = 35,
                            SignalFormFieldId = 15,
                            Validation = 5,
                            Value = "75"
                        },
                        new
                        {
                            Id = 36,
                            SignalFormFieldId = 16,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 37,
                            SignalFormFieldId = 16,
                            Validation = 4,
                            Value = "-75"
                        },
                        new
                        {
                            Id = 38,
                            SignalFormFieldId = 16,
                            Validation = 5,
                            Value = "-10"
                        },
                        new
                        {
                            Id = 39,
                            SignalFormFieldId = 17,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 40,
                            SignalFormFieldId = 18,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 41,
                            SignalFormFieldId = 19,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 42,
                            SignalFormFieldId = 20,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 43,
                            SignalFormFieldId = 21,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 44,
                            SignalFormFieldId = 22,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 45,
                            SignalFormFieldId = 23,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 46,
                            SignalFormFieldId = 24,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 47,
                            SignalFormFieldId = 25,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 48,
                            SignalFormFieldId = 26,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 49,
                            SignalFormFieldId = 27,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 50,
                            SignalFormFieldId = 29,
                            Validation = 1,
                            Value = ""
                        },
                        new
                        {
                            Id = 51,
                            SignalFormFieldId = 30,
                            Validation = 1,
                            Value = ""
                        });
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormAdditionalData", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.SignalFormField", "SignalFormField")
                        .WithMany("AddionalData")
                        .HasForeignKey("SignalFormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignalFormField");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormField", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.SignalForm", "SignalForm")
                        .WithMany("FormFields")
                        .HasForeignKey("SignalFormId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SignalForm");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormOption", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.SignalFormField", "SignalFormField")
                        .WithMany("Options")
                        .HasForeignKey("SignalFormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignalFormField");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormValidation", b =>
                {
                    b.HasOne("RepositoryLayer.Entity.SignalFormField", "SignalFormField")
                        .WithMany("Validations")
                        .HasForeignKey("SignalFormFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignalFormField");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalForm", b =>
                {
                    b.Navigation("FormFields");
                });

            modelBuilder.Entity("RepositoryLayer.Entity.SignalFormField", b =>
                {
                    b.Navigation("AddionalData");

                    b.Navigation("Options");

                    b.Navigation("Validations");
                });
#pragma warning restore 612, 618
        }
    }
}
